### ISSUE TITLE
Command arg parsing producing wierd results

### ISSUE THREAD

**Issue by Deothrin** [dthree/vantage#10]
Not sure if I misunderstood the command arguments - I would like a command with one mandatory arg and one optional. And another command with 2 optional args.

Using

`.command('load <must> [maybe]')`

The command becomes:

`load <must>`

and the args passed to parseExpectedArgs are:

`[ '[maybe]' ]`

In the second instance

`.command(load [maybe] [maybe2])`

The command becomes

`load`

and the args passed to parseExpectedArgs are:

`[ '[maybe] ', 'maybe2]' ]`

notice the missing bracket.

Matt

**Comment by dthree** [comment]
Thanks for the feedback.

Don't yet support variadic arguments, which is what I think you are looking for. This is on the roadmap, but I'm handling a few other things first.

Are you able to get by using a single argument and options?

**Comment by dthree** [comment]
Gonna close this, but if you have more questions, ask anyway and I'll answer!
