### ISSUE TITLE
More explanation?

### ISSUE THREAD

**Issue by young-steveo** [dthree/vantage#11]
I'm intrigued...   but I don't get it.  What exactly is this for?  I get `comander.js`, but this lib somehow exposes a cli to my existing app in production?  I'm not sure I get it.  :(

**Comment by dthree** [comment]
Thanks for your question.

It basically sets up a back door to get into your running application, and lets you do any and everything you set it up to be able to do while the app is running. It's sort of like SSH for node.

Imagine a linux server that you could configure, then start, and then never get into unless you started it in single user mode. That wouldn't be workable. Fortunately, you can SSH into it, and do whatever you want. 

All Vantage does is give you an opportunity to do something similar with node. There's a ton of possibilities.

Alex Young from DailyJS was nice enough to make a whole article about it, and he does a much better job at explaining it than I do:

http://dailyjs.com/2015/06/23/add-a-cli-to-node-apps-with-vantage/

Let me know if this helps.

**Comment by dthree** [comment]
Gonna close this, but if you have more questions, ask anyway and I'll answer!

**Comment by young-steveo** [comment]
Gotcha, thanks!

**Comment by dthree** [comment]
No probs. Will be adding some visuals to the readme soon, which also show what it does much better (plus a few new features).
