### ISSUE TITLE
Expose delimiter to commander?

### ISSUE THREAD

**Issue by joesonw** [dthree/vantage#13]
Allows for later change delimiter in the process of a command. Similarly, it'd good to expose all other run-time related system variables for more featured plugins.

Say, it would be awesome to replace the delimiter after a login?

**Comment by dthree** [comment]
Good idea. I'm currently working on a refactor (authentication fork), and I'll throw the delimiter feature into that. Out of town for about a week, but should be able to jump on this after that. 

Could you please amplify on what you mean by exposing related system variables? One of the refactors of this fork is that the `this` in a Command `action` exposes a Session object which custom functions, so I should be able to tack on additional data to it pretty cleanly. Do you mean environmental variables? Please expand on that.

**Comment by joesonw** [comment]
@dthree I am currently working on a user/group(linux like) module for vantage(including login stuff). In the process, I found it would be useful to get hands on `delimiter`. For the rest of it, I haven't come up with other stuff yet. 

I know I can get a lot of information through this. But there are some variables (and some I don't know about it yet) are pre-configured (like `delimiter`), that are not mutable during runtime.

**Comment by joesonw** [comment]
@dthree it would great to make `vantage` command and `use` command as plugable middlewares. So developers can use it if they need it.

**Comment by dthree** [comment]
Gotcha. Should be back in a few days. If you are still working on auth middleware before then, try to use what I have so far for basic auth as a model for this:

https://github.com/dthree/vantage/blob/authentication/lib/vantage-auth-basic.js

The auth fork is broken right now, but the general form for an auth middleware function is pretty solid as given in the above.

**Comment by dthree** [comment]
@joesonw this is now good to go - do you want to try this out?
