### ISSUE TITLE
Web client

### ISSUE THREAD

**Issue by PymZoR** [dthree/vantage#20]
Hi,
congratulations for this very nice project !
I would like to know if a web client was planned. If not, have you any recommandations to start making one ?

**Comment by dthree** [comment]
Thanks!

Do you mean like a web debugger / profiller? If so, check out Node Inspector:

https://github.com/node-inspector/node-inspector

This does that really well and I wouldn't want to tread on its toes.

If you meant something else, could you please amplify for me?

**Comment by dthree** [comment]
Closing this, but you can still reply / ask more questions!

**Comment by sandrinodimattia** [comment]
I think the question is more about using this in the browser (eg: with browserify). Together with an UI library [like this one](http://terminal.jcubic.pl/#demo) this would be great.

**Comment by dthree** [comment]
Ah - that makes sense. Yeah, that would be kind of awesome.

Perhaps vantage could have an addon made that made it a web server and it could just throw over the interface pre-packaged into it.

i.e., I listen with vantage on port 80, and then if I browser to localhost:80/vantage, it could return a browser-based 'console'.
