### ISSUE TITLE
Feature request: reload when the server code changes

### ISSUE THREAD

**Issue by 3melectronicmonitoring** [dthree/vantage#22]
I don't know if this is ideal but I was trying vantage and thought it would be nice to have a live reload when I change/add vantage commands.

**Comment by dthree** [comment]
Thanks for the input. There's a Node module called `nodemon`: 

https://github.com/remy/nodemon

It does just does that! 

If you want to only reload on Vantage commands and not the application state, you could probably pretty easily make a Vantage extension for that (vantage-watch or something). Then you could throw all of your Vantage commands into one file, and do something like this:

```js

var watch = require("vantage-watch");

vantage.use(watch, {
  files: ['./lib/vantage.commands.js']
});
```

You can have it look for changes in that file, and then simply run that file again, which would re-load in all the vantage commands. 

That would be awesome - and then you could make it on the awesome-vantage list :)

https://github.com/vantagejs/awesome-vantagejs

**Comment by sidthekidder** [comment]
I tried out your suggestion and this is what I came up with - 
https://github.com/sidthekidder/vantage-watch/blob/master/lib/index.js
Nodemon needs a script file as well to start/restart (https://github.com/remy/nodemon/blob/master/doc/requireable.md) so the user has to pass in a ```files``` array as well as a ```script``` filename. 

Is this what you were aiming at? Asking since I'm not sure what CLI options should this have.

**Comment by dthree** [comment]
@sidthekidder thanks and you had the right idea. I happened to be working on this earlier today and was just wrapping up, so I think we're all good now:

https://github.com/vantagejs/vantage-watch

Sid and @3melectronicmonitoring , see if this works out for you! Let me know if there's any details missing that you would find helpful.

**Comment by 3melectronicmonitoring** [comment]
Looks good to me.

**Comment by dthree** [comment]
Okay good.
