### ISSUE TITLE
support more than one parameter

### ISSUE THREAD

**Issue by esnunes** [dthree/vantage#23]
I've tried to create a command with more than one parameters however the library seems not to support it.

code:
```js
vantage
  .command('dbs create <name> <username> <password>', 'creates database')
  .action(require('./cmds/dbs-create'));
```
help output:
```bash
    dbs create <name>>  creates database
```

action args:
```js
[{ options: {}, 'name>': 'a' }]
```

**Comment by dthree** [comment]
Thanks for your input. Yeah, Vantage doesn't yet support variadic arguments, but you're the second person who asked for it, so I should probably get it supported!

**Comment by dthree** [comment]
Thanks for your help.

I took your pull request and used the code, and just finished it up. It needed some changes in a few more places + tests.

Variadic args are fully supported now! :fire:
