### ISSUE TITLE
how to use vantage with cluster ?

### ISSUE THREAD

**Issue by moshir** [dthree/vantage#27]
Is there any guidelines of how to use vantage with an "clustered" express app ?

**Comment by dthree** [comment]
Haven't really tried it out - but could you please explain a little more - is express listening on a bunch of different ports? Or just one port and then it routes the requests to a cluster of workers?

**Comment by moshir** [comment]
Master is listening to one port and forwards requests to N workers.
It's a shared nothing model ...

**Comment by dthree** [comment]
Okay - you can have each worker start its own instance of Vantage, and have each listen on a back port. Or, you can have the master listen with vantage and just connect there.

For example, each worker could be given a port (say 8850 - 8865), and then each could be logged into separately with Vantage if need be.

**Comment by dthree** [comment]
Closing this for now, but do let me know if that worked out!
