### ISSUE TITLE
Connect by domain name

### ISSUE THREAD

**Issue by e-jigsaw** [dthree/vantage#32]
Hi,

I tried to connect remote server with vantage

```
$ vantage some.domain.com:3000
```

then vantage showed `Invalid server/port passed` error. I checked code https://github.com/dthree/vantage/blob/master/bin/vantage.js#L46 . This only passed `x.x.x.x` style ip. So I changed code below

```javascript
  var valid = (isNaN(connection.port))
    ? ("\n  Invalid server/port passed: " + connection.server + ":" + connection.port + "\n")
    : true;
  return valid;
```

And re-run

```
$ vantage some.domain.com:3000
Connecting to some.domain.com:3000 using http...
$ 
```

It works.

Could you remove that validator? or do you have any reason about that validator?

Thanks

**Comment by dthree** [comment]
Nice and thanks for the detail in your issue.

I don't have any good reason for not doing that - I didn't realize it would auto-resolve the DNS - didn't put too much thought to that.

Would you mind doing a pull request on that? If that's too much, let me know and I'll try to fix it as soon as possible.

**Comment by e-jigsaw** [comment]
@dthree I requested fix up this issue. Is this good?

Thanks

**Comment by dthree** [comment]
Yeah all good. Thanks!
