### ISSUE TITLE
1.4.0 remote connection seem to be broken

### ISSUE THREAD

**Issue by mulyoved** [dthree/vantage#36]
Had a code work fine 1.3.5

Deploy and pull vantage 1.4.0 connect don't fail and do get events for connection but don't get prompt and cannot send commands.

Downgrade to 1.3.5 fixed the problem.

**Comment by dthree** [comment]
Ok got it. Checking it out and should be fixed today. Stick on 1.3.5 and I'll let you know when its fixed.

**Comment by dthree** [comment]
I couldn't reproduce this. Perhaps I hadn't published an update after a fix or something... 

I just did a few small fixes and re-published. Can you try again please?

**Comment by mulyoved** [comment]
Just took 1.5.0 and seem to work fine, thanks for the fast answer and great project.

**Comment by dthree** [comment]
Good and thanks!
