### ISSUE TITLE
debug doesn't seem to work within vantage?

### ISSUE THREAD

**Issue by clonq** [dthree/vantage#39]

**Comment by dthree** [comment]
Could you please clarify what you mean by that?

**Comment by clonq** [comment]
sorry, i was talking about the [debug module](https://github.com/visionmedia/debug):
```
vantage.command('test, 'test).action(function(){ require('debug')('test')('whatever); });
```

**Comment by dthree** [comment]
Oh - got it. Could you let me know what happens, i.e. what's expected and what actually happens?

**Comment by clonq** [comment]
Well I'm expecting 'whatever' to be displayed in the console if I set the DEBUG env var to 'test'. It doesn't.

**Comment by dthree** [comment]
K ill check this out.

**Comment by dthree** [comment]
Did you manage to figure this out?

**Comment by clonq** [comment]
Apparently it is working... The only thing I didn't figure out yet is how to get the prompt back after a debug line gets displayed. I need to press a key to get the prompt back. Any suggestions?

**Comment by dthree** [comment]
When you use vantage.log, Vantage does some fancy prompt work to solve that problem of the prompt disappearing. Debug just goes to console.log, so try to bind debug.log to vantage.log. Maybe something like this:

```js
var logger = debug('namespace');
logger.log = vantage.log.bind(vantage);
```

**Comment by clonq** [comment]
That seems to work, thanks!

**Comment by dthree** [comment]
No probs :)

Btw, watching Revo come along - looks great!

I just made an extension you might find helpful, to show people how Revo works:

https://github.com/vorpaljs/vorpal-tour

If you want to see a live demo of the tour in action, just do:

```js
$ npm install -g wat
$ wat tour
```

**Comment by clonq** [comment]
Thanks! The tour extension seems interesting. I'll give it a try.

**Comment by dthree** [comment]
Cool :)
