### ISSUE TITLE
Doesn't work with Node 4 yet

### ISSUE THREAD

**Issue by joe-adams** [dthree/vantage#41]
I'd probably just say it on the chat if I could get on from work, but I accidentally found that it doesn't work with Node 4.  There are node-gyp problems.

**Comment by dthree** [comment]
Hmmm. `Socket.IO` is the only thing that uses `node-gyp`, so it might be a socket.io problem. What's the error?

**Comment by r1cebank** [comment]
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace
      'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/siyuangao/.node-gyp/4.4.0/include/node/node_buffer.h:31:40: note:
      candidate function not viable: no known conversion from 'uint32_t'
      (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,

and the list goes on, i haven't experience any issue working with Socket.io by itself.
