### ISSUE TITLE
child process

### ISSUE THREAD

**Issue by clonq** [dthree/vantage#43]
What is the right way to start another process from within vantage and return to the vantage prompt when the process is terminated via ^C?

**Comment by dthree** [comment]
What happens when you do it now?

**Comment by clonq** [comment]
Exits the main app

**Comment by clonq** [comment]
Solved it by controlling the child process through fork/kill

**Comment by clonq** [comment]
Solved it by controlling the child process through fork/kill

**Comment by dthree** [comment]
Nice! I should probably add this to the docs. Could you give me some example code?

**Comment by clonq** [comment]
Nothing special:
in runApp(appName):
...
        var child = require('child_process').fork(appName);
        runningApps[appName] = child;
...
in stopApp(appName):
...
            runningApps[appName].kill();
...

**Comment by dthree** [comment]
Thanks.
