### ISSUE TITLE
Frozen caret/pointer/cursor.

### ISSUE THREAD

**Issue by METACEO** [dthree/vantage#44]
With:
* Node `v4.0.0`
* Vantage `1.5.1`

Below I typed `foo` with everything going fine...
![type_text](https://cloud.githubusercontent.com/assets/13586713/9894248/34eacf78-5be7-11e5-9958-beb4018559e5.png)
...I then click the left arrow three times, all the while the caret/pointer/cursor remained still. Whenever I press a key, the input appears where I'd expect but the caret/pointer/cursor remains at the end.

![type_text2](https://cloud.githubusercontent.com/assets/13586713/9894249/383baf30-5be7-11e5-9851-3a627d617742.png)

I hope the development with this and Vorpal is working out!

**Comment by dthree** [comment]
Thanks. Just did a Vorpal update that fixed some of these things, so I should push it to Vantage shortly.
