### ISSUE TITLE
Command arguments

### ISSUE THREAD

**Issue by prozacgod** [dthree/vantage#46]
The documentation for command arguments seems to be severely lacking, 

It took a while for me to realize that the .command() function takes some sort of DSL to manage arguments.

And on top of that they don't support quoted strings or something, or perhaps that's more lack of documentation.

In any event it might be helpful to include command argument processing in the simple basic example that's plastered in the readme and pops up everywhere I do a google search

**Comment by dthree** [comment]
Gotcha. Are you referring to [Vorpal](https://github.com/dthree/vorpal/)'s documentation lacking on the command args? I believe I'm pretty thorough in Vorpal's docs, and Vantage just extends Vorpal.

If that's the problem, I can add more links to specific sections of Vorpal's docs from Vantage's readme so its a lot clearer.

**Comment by dthree** [comment]
Closing this for now. Please let me know if I'm missing something and then I'll re-open.
