### ISSUE TITLE
[Question] How well does this interop with process managers like PM2? [eom]

### ISSUE THREAD

**Issue by matthiasak** [dthree/vantage#49]
Would love to figure out how best to integrate this with a process manager like PM2. Any words of wisdom?

**Comment by dthree** [comment]
I haven't tried that yet, but it should be pretty straightforward. Key part is integrating the `stdout` and `stdin`, which can be done. When you've finished, you can probably package it into a module for re-usability.

If you get started on it, I'll gladly coach you along any troubles!
