### ISSUE TITLE
Two arguments to command() produces "vantage.command(...).option is not a function"

### ISSUE THREAD

**Issue by timoxley** [dthree/vantage#5]
If you supply a second argument to `.command()`, it returns the vantage instance rather than the command instance.

The following example from the readme produces an error:

> TypeError: vantage.command(...).option is not a function

```js
const Vantage = require('vantage')
const vantage = new Vantage()

vantage
  .command('order pizza [type]', 'Orders a type of food.')
  .option('-s, --size <size>', 'Size of pizza.')
  .option('-a, --anchovies', 'Include anchovies.')
  .option('-p, --pineapple', 'Include pineapples.')
  .option('-o', 'Include olives.')
  .option('-d, --delivery', 'Pizza should be delivered')
  .action(function(args, cb){
    console.log(args);
    cb();
  });
```

It seems this is done intentionally:

https://github.com/dthree/vantage/blob/361ae73097644c3b208ef2d059104a967983b7c1/lib/vantage.js#L519
```js
vantage.command = function(name, desc, opts) {
  ...
  if (desc) return this;
  return cmd;
};
```

As this came in with the [initial commit](https://github.com/dthree/vantage/commit/f5b04d23c846ce89f54a4f499623d325bf8d6cf7#diff-b967f2d279ebcf3d35281aea272f862eR300), I can't deduce as to why.

**Comment by dthree** [comment]
Most of the command functionality was taken by me from TJ's Commander JS, and in the transition I must have missed this, and managed to miss writing a test for it. I was mainly using `command(...).description(...)` so didn't notice. Should be fixed today.

**Comment by dthree** [comment]
Fixed and added tests.
