### ISSUE TITLE
Can't get auth to work

### ISSUE THREAD

**Issue by jluchiji** [dthree/vantage#52]
No matter what I did, including trying out the builtin `basic` auth mechanism, vantage seems to bypass the authentication every time. For example, the following code results in a successful connection:

```js
const Vantage = require('vantage');

Vantage()
  .delimiter('demo~$')
  .auth(function(vantage, options) {
    return function(args, cb) {
      cb('Nope', false);
    }
  })
  .listen(3001);
```

```sh
$ vantage 3001
```

I tried both on local machine, and on another machine on the same network.
I am currently using version 1.5.2

**Comment by zakhenry** [comment]
@jluchiji I have the same issue, on further investigation it looks like there was a refactoring mistake meaning the auth method was registered to the wrong layer. Fixed in #63
