### ISSUE TITLE
Support multiple HapiJS connections 

### ISSUE THREAD

**Issue by davemackintosh** [dthree/vantage#58]
Hapi has support for multiple connections and no connections at all (like `examples/hapi/hapi.js`), I see three branches of operation here.

1. Create a connection for Socket.IO to hook onto if no connections are present
2. use Hapi labels to label connections and select an appropriate one when creating the Socket.IO server.
3. Use a single connection if only one is present.

**Comment by davemackintosh** [comment]
@dthree ?

**Comment by dthree** [comment]
Merged. Thanks for your help!
