### ISSUE TITLE
listen should take a callback

### ISSUE THREAD

**Issue by timoxley** [dthree/vantage#6]
.listen should take a callback as optional last argument, in the same way net/http `server.listen(port, cb)` does so you know if and when the server bound to the port.

**Comment by dthree** [comment]
No probs and I agree. Should be a quick fix.

**Comment by dthree** [comment]
Okay, this is now supported. The readme has been updated as well as tests.

You can pass it in as the 2nd or 3rd param, as the 2nd can be used for options as well.
