### ISSUE TITLE
Suppress internal logs

### ISSUE THREAD

**Issue by timoxley** [dthree/vantage#7]
Need a way to disable these types of messages:

```
User entering session.
Piping stdout downstream.
Stdout returned to console.
User exited session.
```

**Comment by dthree** [comment]
Their not really necessary at all I guess. Do you think I should just get rid of them?

Whatever your best judgement is, I'll take. Your Tim Oxley. I've been in the open source community for a total of 3 weeks :)

**Comment by dthree** [comment]
Fixed and updated readme.

If you pass in the `logActivity: true` option on `vantage.listen`, the messages will show. Defaults to `false`.
